server:
  port: 3000

db:
  type: 'mysql'
  port: 3306
  database: 'daesonamu'
  username: 'root'
  host: 'localhost'
  password: 'Tw080401!!**'
  synchronize: true

jwt:
  expiration: 3600
  secret: 'serverofdaesonamu'
  refreshSecret: "refreshdaesonamu"
  refreshExpiration: 2592000
